# Generated by Django 6.0 on 2026-01-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=10)),
                ('roll', models.IntegerField(max_length=10)),
                ('branch', models.CharField(max_length=10)),
            ],
        ),
    ]
